# Add application configuration variables here, as shown below.
#

AMAZON_SES_ACCESS_KEY: AKIAJU443HCUVNV44RCA
AMAZON_SES_SECRET_KEY: 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



AMAZON_S3_ACCESS_KEY: AKIAJU443HCUVNV44RCA
AMAZON_S3_SECRET_KEY: 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
