# Add application configuration variables here, as shown below.
#

AMAZON_SES_ACCESS_KEY: put_your_key_here_when_deploy_to_prod
AMAZON_SES_SECRET_KEY: put_your_key_here_when_deploy_to_prod

AMAZON_S3_ACCESS_KEY: put_your_key_here_when_deploy_to_prod
AMAZON_S3_SECRET_KEY: put_your_key_here_when_deploy_to_prod
